spring:
  datasource:
    url: jdbc:mysql://localhost:3306/novel_app?characterEncoding=utf8&useSSL=true
    username: root
    password: chsqc578480
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/mappers/*.xml